name: Testing

on: [pull_request, push]

jobs:
  test:
    runs-on: windows-2022
    steps:
    - name: Execute
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x86_amd64
      shell: cmd
    - name: Tools
      run: |
        echo %vctoolsversion%
      shell: cmd
    - name: Dir
      run: |
        dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC"
      shell: cmd
